### ISSUE TITLE
Changing themes?

### ISSUE THREAD

**Issue by Commiee** [ReGuilded/ReGuilded#20]
This will be a very newb question - how do I change themes after installation? After clicking 'inject', I relaunched Guilded and see the theme that I guess comes with ReGuilded, but can't find any menu/selection with list of other themes.

**Comment by ZaneDragonBorn** [comment]
ReGuilded currently doesn’t have a In-app Settings menu. However you can get a Add-on known as “SettingsInjector” to offer that. For now, you will have to change your Settings from `%appdata%/.reguilded/settings`. An In-app settings menu is planned for ReGuilded V0.0.3

**Comment by Commiee** [comment]
Thank you. As far as I can tell from the readme file there, there is no way of only replacing the background image in a theme?

**Comment by ZaneDragonBorn** [comment]
With the default theme, DreamFrame. You can change it by going to your Themes folder and opening the CSS file. It’s going to be the Import thing.

**Comment by Commiee** [comment]
Thank you.
