### ISSUE TITLE
[Serious] License/Permission Issues Found in This Project (should be resolved soon)

### ISSUE THREAD

**Issue by MasicoreLord** [ReGuilded/ReGuilded#25]
> NOTE: Due to some mistakes NATHANIEL made while developing ReGuilded, we're dealing with some legal issues we would like to avoid. Contributing to ReGuilded outside of the Organization has now been disabled. It will be enabled once we can resolve these issues.

> To the developers of Powercord from Nathaniel:
I'm deeply sorry for my actions, and not asking for permission to use your Patcher code is most noticeable here. I would like to resolve this as peacefully as possible, with little-to-no damage done. This mistake is entirely my own, and none of the other Contributors to ReGuilded.

> You can reach me on Discord: `Nathaniel.#0001`
I also already have a message out to you all.
- @ItzNxthaniel
Source: https://github.com/ReGuilded/ReGuilded/commit/ba6a55347e6d5437f77baffaad357c16af141df5

**Comment by ItzNxthaniel** [comment]
Due to this issue, full development on ReGuilded has been halted, and will be resumed when we can resolve this issue.

**Comment by ItzNxthaniel** [comment]
After speaking with Powercord License Holders, we've come to a resolution, and this issue is now closed.
