### ISSUE TITLE
Hyperlinks causes RG and Guilded to stop loading

### ISSUE THREAD

**Issue by ny404** [ReGuilded/ReGuilded#27]
Please see attached video!

https://user-images.githubusercontent.com/38796514/149572651-0973f7db-5d84-4371-936a-11715ab19083.mp4

**Comment by ItzNxthaniel** [comment]
We've found an error relating to this issue, and will look into this:
`"Render frame was disposed before WebFrameMain could be accessed"`

**Comment by IdkGoodName** [comment]
Fixed with commit e8f39ef.

**Comment by ItzNxthaniel** [comment]
Confirmed to still be broke.

**Comment by ItzNxthaniel** [comment]
Okay, we're pretty sure this issue has been fixed, and the issue was still present due to a local repo mishap.
