### ISSUE TITLE
No Refresh on Check For Updates (most likely)

### ISSUE THREAD

**Issue by MasicoreLord** [ReGuilded/ReGuilded#29]
![image](https://user-images.githubusercontent.com/11468845/151215063-1a1bbdde-4c4c-42a3-bb6e-9433085d1350.png)

**Comment by MasicoreLord** [comment]
Comment above w/ proposed solution

**Comment by ItzNxthaniel** [comment]
After looking at the code, it doesn't seem like we do this. As well as the auto-update code being all the way in the ReGuilded Core file.

We would want auto-update to run before ReGuilded Core has any chance to run, to minimize running ReGuilded Core File.

I propose, we move the auto-update check & call to be in the preload, right before we run ReGuilded.init(), we wait until we get a resolution from the update Promise. If an update has been done, we force reload the screen, and the user should just see a little blimp and then back to the Guilded Loading Splash. The update would/should be completely silent to the user.

I'll get this change done later today.

**Comment by ItzNxthaniel** [comment]
Closed by 759e447
