### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by githubmodssuck** [ReGuilded/ReGuilded#32]

**Comment by ItzNxthaniel** [comment]
What do you mean Not Loading?

**Comment by githubmodssuck** [comment]
Whenever I load guilded there's no install button

**Comment by ItzNxthaniel** [comment]
Are you talking about the installer? Found on [ReGuilded-Installer](https://github.com/reguilded/reguilded-installer)?

**Comment by ItzNxthaniel** [comment]
I'm gonna go ahead and close this, this was before we released v0.0.4-alpha. Going to say that this was about the installer not displaying any downloads cause we were still working on the update.
