### ISSUE TITLE
Open Directory Button does nothing

### ISSUE THREAD

**Issue by ZaneDragonBorn** [ReGuilded/ReGuilded#34]
The Current Open directory button for Themes doesn't take me anywhere. Below is a screenshot of the error in Console
![image](https://user-images.githubusercontent.com/68198648/156250296-6c2a5398-b070-4847-a05f-b643b690505e.png)

**Comment by ItzNxthaniel** [comment]
Thank you for your report, we'll look into fixing this asap!

**Comment by ZaneDragonBorn** [comment]
Reopening issue, Although fixed in Options, the Enhancement overview button is still using broken code.
