### ISSUE TITLE
[Bug] Sizing issues on Default Theme

### ISSUE THREAD

**Issue by ZaneDragonBorn** [ReGuilded/ReGuilded#5]
There are a few different sizing Bugs with the Theme that I found. Will add more when I see them.

![Screenshot_22](https://user-images.githubusercontent.com/68198648/123484332-28410700-d5d6-11eb-8d39-6c04964238d6.png)
_Emote Button is Out of Frame_

![image](https://user-images.githubusercontent.com/68198648/123484450-5b839600-d5d6-11eb-9956-1b7a86ff0170.png)
_Can't access the Right side of the Media_

**Comment by ZaneDragonBorn** [comment]
Found another one
![image](https://user-images.githubusercontent.com/68198648/123872161-af59ec00-d902-11eb-9706-305261092197.png)
Also, Most of the Menus in Legacy nav having gotten any Theming. Wouldn't mind seeing those get added!

**Comment by IdkGoodName** [comment]
Not related to ReGuilded. This is theme's fault.
