### ISSUE TITLE
Theme error: Error Minified React error

### ISSUE THREAD

**Issue by NotAussie** [ReGuilded/ReGuilded#53]
Can only show images due to the copy button not working, sorry if it's hard to read. Also, to whoever reads this I hope you have a lovely day!

![image](https://github.com/ReGuilded/ReGuilded/assets/123055696/3e2a2e16-1c08-4094-bd5a-cee2b3110b9a)

![image](https://github.com/ReGuilded/ReGuilded/assets/123055696/a29249ca-fc5f-48e8-b249-0dee40aaf59c)

![image](https://github.com/ReGuilded/ReGuilded/assets/123055696/7204495b-bb52-47c2-b708-916cd5bed1c7)

![image](https://github.com/ReGuilded/ReGuilded/assets/123055696/e32fd158-e45f-4956-911c-d91416a94372)

![image](https://github.com/ReGuilded/ReGuilded/assets/123055696/c7ad6eb1-6113-427a-9e06-0de2cd2d95ed)

![image](https://github.com/ReGuilded/ReGuilded/assets/123055696/f2640bd6-12f7-4a46-9f53-2e8d9706c616)

**Comment by ItzNxthaniel** [comment]
Duplicate of #52
