### ISSUE TITLE
ReGuilded client pulling non-existent content

### ISSUE THREAD

**Issue by NotAussie** [ReGuilded/ReGuilded#56]
When the ReGuilded client loads it tries to pull `https://raw.githubusercontent.com/ReGuilded/ReGuilded-Website/main/ReGuilded/wwwroot/contributorIds.json`, but the route only returns 404.

**Comment by Blocksnmore** [comment]
Taking a look at the git history it seems this happened when ReGuilded's website switched to Next.js as [This Commit](https://github.com/ReGuilded/ReGuilded-Website/commit/e8978bacb5389e13b9ab5481483d52f9e887955b) deleted the files.

**Comment by Blocksnmore** [comment]
This issue should probably be closed as it was fixed in [b501e9a (Website)](https://github.com/ReGuilded/ReGuilded-Website/commit/b501e9a3b5574110b481eb4492cf8d01263eb357) and [8e2b5e0 (Client)](https://github.com/ReGuilded/ReGuilded/commit/8e2b5e0e4edc2a0039291c6ab01f3bba91a0797b) respectively

**Comment by ItzNxthaniel** [comment]
> This issue should probably be closed as it was fixed in [b501e9a (Website)](https://github.com/ReGuilded/ReGuilded-Website/commit/b501e9a3b5574110b481eb4492cf8d01263eb357) and [8e2b5e0 (Client)](https://github.com/ReGuilded/ReGuilded/commit/8e2b5e0e4edc2a0039291c6ab01f3bba91a0797b) respectively

Thank you.

**Comment by ItzNxthaniel** [comment]
Fixed in 8e2b5e0
